name: Pantheon Maintenance Deploy

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:

    if: |
      github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'maintenance-') || github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest

    env:
      PANTHEON_ENV: "dev"
      PANTHEON_BRANCH: "master"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, curl, xml, zip, mysql

      - name: Install Terminus
        run: |
          curl -L https://github.com/pantheon-systems/terminus/releases/latest/download/terminus.phar --output /usr/local/bin/terminus
          chmod +x /usr/local/bin/terminus

      - name: Authenticate with Pantheon
        run: terminus auth:login --machine-token="${{ secrets.PANTHEON_MACHINE_TOKEN }}"

      - name: Configure Git
        run: |
          git config user.name "PROVEN MAINTENANCE BOT"
          git config user.email "developers@proven.us"

      - name: Add Pantheon Git Remote
        run: |
          # Establish the environment as git
          terminus connection:set ${{ vars.PANTHEON_PROJECT_NAME }}.${{ env.PANTHEON_ENV }} git

          # Get Pantheon Git URL and set it as a remote
          export PANTHEON_GIT_URL=$(terminus connection:info ${{ vars.PANTHEON_PROJECT_NAME }}.${{ env.PANTHEON_ENV }} --field=git_url)
          git remote add pantheon $PANTHEON_GIT_URL

          echo "PANTHEON_GIT_URL=$PANTHEON_GIT_URL" >> $GITHUB_ENV

          # Check the remotes
          git remote -v

      - name: Setup the SSH Key
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -m PEM -C "developers@proven.us" -f ~/.ssh/id_rsa -N ""
          terminus ssh-key:add ~/.ssh/id_rsa.pub --yes

          PANTHEON_SSH_KEY_DOMAIN=$(echo "${{ env.PANTHEON_GIT_URL }}" | awk -F'[@/]' '{print $4}')

          cat <<EOF >> ~/.ssh/config
          Host *.drush.in
            StrictHostKeyChecking no
          EOF

          # ssh-keyscan -H "$PANTHEON_SSH_KEY_DOMAIN" >> ~/.ssh/known_hosts

      - name: Push code to Pantheon
        run: |
          git fetch pantheon
          git push --force pantheon HEAD:refs/heads/${{ env.PANTHEON_BRANCH }}

      - name: Remove the last SSH Key we Added to Pantheon
        if: always()
        run: |
          # grab the ID and use it to remove the key
          export COLUMNS=256 # So the table displayed by terminus won't split into useless lines

          terminus ssh-key:list

          LAST_SSH_KEY_ID=$(terminus ssh-key:list | grep "developers@proven.us" | awk '{ print $1 }')

          if [ -n "$LAST_SSH_KEY_ID" ] && [ '.' !=  "$LAST_SSH_KEY_ID" ]; then
            echo "$LAST_SSH_KEY_ID" | while IFS= read -r KEY; do
              if [ -n "$KEY" ]; then
                terminus ssh-key:remove "$KEY"
              fi
            done
          fi